FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD target/task-manager-service.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-Dspring.data.mongodb.uri=mongodb://mongodb/micros", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]